import { build } from "esbuild";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const output = resolve(root, "dist");
await mkdir(output, { recursive: true });
const options = { absWorkingDir: root, bundle: true, minify: true, legalComments: "none", metafile: true, write: false };
const app = await build({ ...options, entryPoints: ["src/app.ts"], platform: "browser", target: "es2022", format: "esm" });
const html = (await readFile(resolve(root, "src/app.html"), "utf8"))
  .replace("/*APP_SCRIPT*/", app.outputFiles[0].text.replace(/<\/script/gi, "<\\/script"));
await writeFile(resolve(output, "storage-probe.html"), html);
const server = await build({
  ...options, entryPoints: ["src/server.mjs"], platform: "node", target: "node22", format: "esm",
  banner: { js: "import { createRequire } from 'node:module'; const require = createRequire(import.meta.url);" }
});
await writeFile(resolve(output, "server.mjs"), server.outputFiles[0].text);

const packages = new Set();
for (const path of [...Object.keys(app.metafile.inputs), ...Object.keys(server.metafile.inputs)]) {
  const match = path.match(/(?:^|\/)node_modules\/((?:@[^/]+\/)?[^/]+)/);
  if (match) packages.add(match[1]);
}
let notices = "# Bundled dependency notices\n\nGenerated by npm run build. Applies to the bundled server and UI.\n\n";
for (const name of [...packages].sort()) {
  const directory = resolve(root, "node_modules", name);
  const metadata = JSON.parse(await readFile(resolve(directory, "package.json"), "utf8"));
  let license;
  for (const filename of ["LICENSE", "LICENSE.md", "LICENSE.txt", "LICENSE-MIT", "license", "license.md", "license.txt"]) {
    try { license = await readFile(resolve(directory, filename), "utf8"); break; } catch (error) { if (error.code !== "ENOENT") throw error; }
  }
  if (license == null && name === "@cfworker/json-schema") {
    license = await readFile(resolve(root, "licenses/cfworker-json-schema-LICENSE"), "utf8");
  }
  if (license == null) throw new Error(`No license text found for bundled dependency ${name}.`);
  notices += `## ${name} ${metadata.version}\n\nLicense: ${metadata.license ?? "See text below"}\n\n${license.trim()}\n\n`;
}
await writeFile(resolve(root, "THIRD-PARTY-NOTICES.md"), notices.trimEnd() + "\n");
console.log("Built self-contained server, HTML editor, and dependency notices.");
