// <auto-generated />
using System;
using Lorekeeper.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lorekeeper.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260525050358_AddInlineContestReview")]
    partial class AddInlineContestReview
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Lorekeeper.Models.Act", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Synopsis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Order");

                    b.ToTable("Acts");
                });

            modelBuilder.Entity("Lorekeeper.Models.AiChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AfterJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ArgumentsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BeforeJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedResourceIdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DependsOnChangeIdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DraftAfterJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReferencedResourceIdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RejectionMessage")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceKind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewStateJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolCallId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("BatchId", "Order");

                    b.ToTable("AiChanges");
                });

            modelBuilder.Entity("Lorekeeper.Models.AiChangeBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AssistantMessageId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConversationKind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Status", "CreatedAt");

                    b.ToTable("AiChangeBatches");
                });

            modelBuilder.Entity("Lorekeeper.Models.Chapter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Synopsis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("VectorIndexError")
                        .HasColumnType("TEXT");

                    b.Property<string>("VectorIndexState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("VectorIndexedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActId", "Order");

                    b.HasIndex("ProjectId", "Order");

                    b.ToTable("Chapters");
                });

            modelBuilder.Entity("Lorekeeper.Models.ContestBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AcceptedChapterBody")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AssistantMessageId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ChapterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChapterTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContextSnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalChapterBody")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("WinningCandidateId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId", "CreatedAt");

                    b.HasIndex("ProjectId", "Status", "CreatedAt");

                    b.ToTable("ContestBatches");
                });

            modelBuilder.Entity("Lorekeeper.Models.ContestCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("DurationMs")
                        .HasColumnType("REAL");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MutationsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProposedBody")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProviderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RawResponse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewStateJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BatchId", "Order");

                    b.ToTable("ContestCandidates");
                });

            modelBuilder.Entity("Lorekeeper.Models.EditorContextPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ChapterId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsIncluded")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.HasIndex("ProjectId", "ChapterId", "SortOrder");

                    b.HasIndex("ProjectId", "ChapterId", "Kind", "Key")
                        .IsUnique();

                    b.ToTable("EditorContextPreferences");
                });

            modelBuilder.Entity("Lorekeeper.Models.EditorConversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("EditorConversations");
                });

            modelBuilder.Entity("Lorekeeper.Models.EditorMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolCallId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolCallsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId", "Order");

                    b.ToTable("EditorMessages");
                });

            modelBuilder.Entity("Lorekeeper.Models.EditorRevisionJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ArgumentsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AssistantMessageId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolCallId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId", "CreatedAt");

                    b.HasIndex("ProjectId", "Status", "CreatedAt");

                    b.ToTable("EditorRevisionJobs");
                });

            modelBuilder.Entity("Lorekeeper.Models.EditorRevisionMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolCallId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolCallsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "Order");

                    b.ToTable("EditorRevisionMessages");
                });

            modelBuilder.Entity("Lorekeeper.Models.EditorRevisionSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ChapterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChapterTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("DurationMs")
                        .HasColumnType("REAL");

                    b.Property<int?>("EndLine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MutationKind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalChapterBody")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProposalJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProviderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RawResponse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplacementText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("StartLine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId", "CreatedAt");

                    b.HasIndex("JobId", "Order");

                    b.ToTable("EditorRevisionSessions");
                });

            modelBuilder.Entity("Lorekeeper.Models.EmbeddingConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiKind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Dimensions")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastTestedApiKind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastTestedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("LastTestedDimensions")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastTestedModelId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LastTestedProviderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProviderId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId");

                    b.ToTable("EmbeddingConfigurations");
                });

            modelBuilder.Entity("Lorekeeper.Models.GraphEdge", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EdgeType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FromNodeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Properties")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ToNodeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FromNodeId", "EdgeType");

                    b.HasIndex("ToNodeId", "EdgeType");

                    b.ToTable("GraphEdges");
                });

            modelBuilder.Entity("Lorekeeper.Models.GraphEntityType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultProperties")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsChapterScoped")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsStructural")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PluralLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SingularLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "SortOrder");

                    b.HasIndex("ProjectId", "Type")
                        .IsUnique();

                    b.ToTable("GraphEntityTypes");
                });

            modelBuilder.Entity("Lorekeeper.Models.GraphNode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT");

                    b.Property<string>("NodeType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Properties")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NodeType");

                    b.HasIndex("ProjectId", "NodeType", "Key")
                        .IsUnique();

                    b.ToTable("GraphNodes");
                });

            modelBuilder.Entity("Lorekeeper.Models.IngestJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CompletedSourceChunks")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedEntityCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreatedRelationshipCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrentMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("EncodingName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelName")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProviderId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalSourceChunks")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId");

                    b.HasIndex("SourceId", "CreatedAt");

                    b.HasIndex("ProjectId", "Status", "CreatedAt");

                    b.ToTable("IngestJobs");
                });

            modelBuilder.Entity("Lorekeeper.Models.IngestJobChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedEntityCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreatedRelationshipCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourceChunkId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceChunkIndex")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceChunkId");

                    b.HasIndex("JobId", "SourceChunkId")
                        .IsUnique();

                    b.HasIndex("JobId", "SourceChunkIndex");

                    b.ToTable("IngestJobChunks");
                });

            modelBuilder.Entity("Lorekeeper.Models.IngestJobEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobId", "CreatedAt");

                    b.ToTable("IngestJobEvents");
                });

            modelBuilder.Entity("Lorekeeper.Models.IngestReportItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("GraphEdgeId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("GraphNodeId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SourceChunkId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GraphEdgeId");

                    b.HasIndex("GraphNodeId");

                    b.HasIndex("SourceChunkId");

                    b.HasIndex("JobId", "Kind", "Status", "CreatedAt");

                    b.ToTable("IngestReportItems");
                });

            modelBuilder.Entity("Lorekeeper.Models.IngestSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CanonicalUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FinalUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceKind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceMetadataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserInstructions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VectorIndexError")
                        .HasColumnType("TEXT");

                    b.Property<string>("VectorIndexState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("VectorIndexedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "CreatedAt");

                    b.ToTable("IngestSources");
                });

            modelBuilder.Entity("Lorekeeper.Models.IngestSourceChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentNotes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("EndChar")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstimatedTokenCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HeadingPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("TEXT");

                    b.Property<int>("StartChar")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StructureStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("TokenCountIsExact")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TokenCountMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenEncodingName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceId", "Index")
                        .IsUnique();

                    b.ToTable("IngestSourceChunks");
                });

            modelBuilder.Entity("Lorekeeper.Models.IngestVectorFragment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("EndChar")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("TEXT");

                    b.Property<int>("StartChar")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("VectorRowId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VectorRowId");

                    b.HasIndex("SourceId", "Index")
                        .IsUnique();

                    b.ToTable("IngestVectorFragments");
                });

            modelBuilder.Entity("Lorekeeper.Models.LlmProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CredentialSourceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndpointUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastChatTestAuthType")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastChatTestCredentialSourceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastChatTestEndpointUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastChatTestError")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastChatTestModelId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LastChatTestSucceeded")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastChatTestedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CredentialSourceId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("LlmProviders");
                });

            modelBuilder.Entity("Lorekeeper.Models.OAuthToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProviderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("Scope")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId");

                    b.ToTable("OAuthTokens");
                });

            modelBuilder.Entity("Lorekeeper.Models.OutlineConversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("OutlineConversations");
                });

            modelBuilder.Entity("Lorekeeper.Models.OutlineMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolCallId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolCallsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId", "Order");

                    b.ToTable("OutlineMessages");
                });

            modelBuilder.Entity("Lorekeeper.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AiChangeApprovalEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ContestModeEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ContestProviderSlot1Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ContestProviderSlot2Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ContestProviderSlot3Id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IncludeCurrentChapterInContext")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Lorekeeper.Models.ProjectImportJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CompletedSteps")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedActCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedBeatCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreatedChapterCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreatedEdgeCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreatedNodeCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrentMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExportKind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FormatId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FormatVersion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MergedEdgeCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MergedNodeCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalSteps")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("WarningCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Status", "CreatedAt");

                    b.ToTable("ProjectImportJobs");
                });

            modelBuilder.Entity("Lorekeeper.Models.ProjectImportReportItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("GraphEdgeId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("GraphNodeId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GraphEdgeId");

                    b.HasIndex("GraphNodeId");

                    b.HasIndex("JobId", "Kind", "Status", "CreatedAt");

                    b.ToTable("ProjectImportReportItems");
                });

            modelBuilder.Entity("Lorekeeper.Models.PublishAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AltText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GenerationModel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceMetadataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "CreatedAt");

                    b.ToTable("PublishAssets");
                });

            modelBuilder.Entity("Lorekeeper.Models.PublishImagePlacement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlacementKind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetKind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("ProjectId", "TargetKind", "TargetId", "PlacementKind", "SortOrder");

                    b.ToTable("PublishImagePlacements");
                });

            modelBuilder.Entity("Lorekeeper.Models.PublishOutlineSelection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsIncluded")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetKind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "TargetKind", "TargetId")
                        .IsUnique();

                    b.ToTable("PublishOutlineSelections");
                });

            modelBuilder.Entity("Lorekeeper.Models.PublishProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Acknowledgments")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Copyright")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverLayoutJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dedication")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IncludeActHeadings")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludeActSynopses")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludeChapterHeadings")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludeChapterSynopses")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludeTableOfContents")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludeVisibleTableOfContents")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("NumberActs")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NumberChapters")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("References")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SelectedCoverAssetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subtitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleOverride")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.HasIndex("SelectedCoverAssetId");

                    b.ToTable("PublishProfiles");
                });

            modelBuilder.Entity("Lorekeeper.Models.ResearchConversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("ResearchConversations");
                });

            modelBuilder.Entity("Lorekeeper.Models.ResearchMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolCallId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolCallsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId", "Order");

                    b.ToTable("ResearchMessages");
                });

            modelBuilder.Entity("Lorekeeper.Models.SearchProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigurationJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SearchProviders");
                });

            modelBuilder.Entity("Lorekeeper.Models.WebIngestCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CachedLinksJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CanonicalUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CrawlDepth")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Diagnostics")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscoveryKind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Excerpt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtractedText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FinalUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("IngestJobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("QueuedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawMetadataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ResearchConversationId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SearchProviderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SearchQuery")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SearchRank")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Snippet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceProviderName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StageRationale")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StagedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IngestJobId");

                    b.HasIndex("ResearchConversationId", "CreatedAt");

                    b.HasIndex("ProjectId", "Status", "CreatedAt");

                    b.ToTable("WebIngestCandidates");
                });

            modelBuilder.Entity("Lorekeeper.Models.WritingCoachConversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("WritingCoachConversations");
                });

            modelBuilder.Entity("Lorekeeper.Models.WritingCoachMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolCallId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolCallsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId", "Order");

                    b.ToTable("WritingCoachMessages");
                });

            modelBuilder.Entity("Lorekeeper.Models.WritingSample", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Title");

                    b.HasIndex("ProjectId", "UpdatedAt");

                    b.ToTable("WritingSamples");
                });

            modelBuilder.Entity("Lorekeeper.Models.Act", b =>
                {
                    b.HasOne("Lorekeeper.Models.Project", "Project")
                        .WithMany("Acts")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Lorekeeper.Models.AiChange", b =>
                {
                    b.HasOne("Lorekeeper.Models.AiChangeBatch", "Batch")
                        .WithMany("Changes")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("Lorekeeper.Models.AiChangeBatch", b =>
                {
                    b.HasOne("Lorekeeper.Models.Project", "Project")
                        .WithMany("AiChangeBatches")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Lorekeeper.Models.Chapter", b =>
                {
                    b.HasOne("Lorekeeper.Models.Act", "Act")
                        .WithMany("Chapters")
                        .HasForeignKey("ActId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Lorekeeper.Models.Project", "Project")
                        .WithMany("Chapters")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Act");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Lorekeeper.Models.ContestBatch", b =>
                {
                    b.HasOne("Lorekeeper.Models.Project", "Project")
                        .WithMany("ContestBatches")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Lorekeeper.Models.ContestCandidate", b =>
                {
                    b.HasOne("Lorekeeper.Models.ContestBatch", "Batch")
                        .WithMany("Candidates")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("Lorekeeper.Models.EditorContextPreference", b =>
                {
                    b.HasOne("Lorekeeper.Models.Chapter", "Chapter")
                        .WithMany("EditorContextPreferences")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lorekeeper.Models.Project", "Project")
                        .WithMany("EditorContextPreferences")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Lorekeeper.Models.EditorConversation", b =>
                {
                    b.HasOne("Lorekeeper.Models.Project", "Project")
                        .WithMany("EditorConversations")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Lorekeeper.Models.EditorMessage", b =>
                {
                    b.HasOne("Lorekeeper.Models.EditorConversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("Lorekeeper.Models.EditorRevisionJob", b =>
                {
                    b.HasOne("Lorekeeper.Models.Project", "Project")
                        .WithMany("EditorRevisionJobs")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Lorekeeper.Models.EditorRevisionMessage", b =>
                {
                    b.HasOne("Lorekeeper.Models.EditorRevisionSession", "Session")
                        .WithMany("Messages")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Lorekeeper.Models.EditorRevisionSession", b =>
                {
                    b.HasOne("Lorekeeper.Models.EditorRevisionJob", "Job")
                        .WithMany("Sessions")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Lorekeeper.Models.EmbeddingConfiguration", b =>
                {
                    b.HasOne("Lorekeeper.Models.LlmProvider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Lorekeeper.Models.GraphEdge", b =>
                {
                    b.HasOne("Lorekeeper.Models.GraphNode", "FromNode")
                        .WithMany("OutgoingEdges")
                        .HasForeignKey("FromNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lorekeeper.Models.GraphNode", "ToNode")
                        .WithMany("IncomingEdges")
                        .HasForeignKey("ToNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromNode");

                    b.Navigation("ToNode");
                });

            modelBuilder.Entity("Lorekeeper.Models.GraphEntityType", b =>
                {
                    b.HasOne("Lorekeeper.Models.Project", "Project")
                        .WithMany("EntityTypes")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Lorekeeper.Models.GraphNode", b =>
                {
                    b.HasOne("Lorekeeper.Models.Project", "Project")
                        .WithMany("Nodes")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Lorekeeper.Models.IngestJob", b =>
                {
                    b.HasOne("Lorekeeper.Models.Project", "Project")
                        .WithMany("IngestJobs")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lorekeeper.Models.LlmProvider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Lorekeeper.Models.IngestSource", "Source")
                        .WithMany("Jobs")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Provider");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("Lorekeeper.Models.IngestJobChunk", b =>
                {
                    b.HasOne("Lorekeeper.Models.IngestJob", "Job")
                        .WithMany("Chunks")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lorekeeper.Models.IngestSourceChunk", "SourceChunk")
                        .WithMany("JobChunks")
                        .HasForeignKey("SourceChunkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("SourceChunk");
                });

            modelBuilder.Entity("Lorekeeper.Models.IngestJobEvent", b =>
                {
                    b.HasOne("Lorekeeper.Models.IngestJob", "Job")
                        .WithMany("Events")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Lorekeeper.Models.IngestReportItem", b =>
                {
                    b.HasOne("Lorekeeper.Models.IngestJob", "Job")
                        .WithMany("ReportItems")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lorekeeper.Models.IngestSourceChunk", "SourceChunk")
                        .WithMany("ReportItems")
                        .HasForeignKey("SourceChunkId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Job");

                    b.Navigation("SourceChunk");
                });

            modelBuilder.Entity("Lorekeeper.Models.IngestSource", b =>
                {
                    b.HasOne("Lorekeeper.Models.Project", "Project")
                        .WithMany("IngestSources")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Lorekeeper.Models.IngestSourceChunk", b =>
                {
                    b.HasOne("Lorekeeper.Models.IngestSource", "Source")
                        .WithMany("SourceChunks")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("Lorekeeper.Models.IngestVectorFragment", b =>
                {
                    b.HasOne("Lorekeeper.Models.IngestSource", "Source")
                        .WithMany("VectorFragments")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("Lorekeeper.Models.LlmProvider", b =>
                {
                    b.HasOne("Lorekeeper.Models.LlmProvider", "CredentialSource")
                        .WithMany("ChildModels")
                        .HasForeignKey("CredentialSourceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CredentialSource");
                });

            modelBuilder.Entity("Lorekeeper.Models.OAuthToken", b =>
                {
                    b.HasOne("Lorekeeper.Models.LlmProvider", "Provider")
                        .WithMany("OAuthTokens")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Lorekeeper.Models.OutlineConversation", b =>
                {
                    b.HasOne("Lorekeeper.Models.Project", "Project")
                        .WithMany("OutlineConversations")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Lorekeeper.Models.OutlineMessage", b =>
                {
                    b.HasOne("Lorekeeper.Models.OutlineConversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("Lorekeeper.Models.ProjectImportJob", b =>
                {
                    b.HasOne("Lorekeeper.Models.Project", "Project")
                        .WithMany("ProjectImportJobs")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Lorekeeper.Models.ProjectImportReportItem", b =>
                {
                    b.HasOne("Lorekeeper.Models.ProjectImportJob", "Job")
                        .WithMany("ReportItems")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Lorekeeper.Models.PublishAsset", b =>
                {
                    b.HasOne("Lorekeeper.Models.Project", "Project")
                        .WithMany("PublishAssets")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Lorekeeper.Models.PublishImagePlacement", b =>
                {
                    b.HasOne("Lorekeeper.Models.PublishAsset", "Asset")
                        .WithMany("ImagePlacements")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lorekeeper.Models.Project", "Project")
                        .WithMany("PublishImagePlacements")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Lorekeeper.Models.PublishOutlineSelection", b =>
                {
                    b.HasOne("Lorekeeper.Models.Project", "Project")
                        .WithMany("PublishOutlineSelections")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Lorekeeper.Models.PublishProfile", b =>
                {
                    b.HasOne("Lorekeeper.Models.Project", "Project")
                        .WithMany("PublishProfiles")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lorekeeper.Models.PublishAsset", "SelectedCoverAsset")
                        .WithMany("CoverProfiles")
                        .HasForeignKey("SelectedCoverAssetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Project");

                    b.Navigation("SelectedCoverAsset");
                });

            modelBuilder.Entity("Lorekeeper.Models.ResearchConversation", b =>
                {
                    b.HasOne("Lorekeeper.Models.Project", "Project")
                        .WithMany("ResearchConversations")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Lorekeeper.Models.ResearchMessage", b =>
                {
                    b.HasOne("Lorekeeper.Models.ResearchConversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("Lorekeeper.Models.WebIngestCandidate", b =>
                {
                    b.HasOne("Lorekeeper.Models.Project", "Project")
                        .WithMany("WebIngestCandidates")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Lorekeeper.Models.WritingCoachConversation", b =>
                {
                    b.HasOne("Lorekeeper.Models.Project", "Project")
                        .WithMany("WritingCoachConversations")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Lorekeeper.Models.WritingCoachMessage", b =>
                {
                    b.HasOne("Lorekeeper.Models.WritingCoachConversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("Lorekeeper.Models.WritingSample", b =>
                {
                    b.HasOne("Lorekeeper.Models.Project", "Project")
                        .WithMany("WritingSamples")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Lorekeeper.Models.Act", b =>
                {
                    b.Navigation("Chapters");
                });

            modelBuilder.Entity("Lorekeeper.Models.AiChangeBatch", b =>
                {
                    b.Navigation("Changes");
                });

            modelBuilder.Entity("Lorekeeper.Models.Chapter", b =>
                {
                    b.Navigation("EditorContextPreferences");
                });

            modelBuilder.Entity("Lorekeeper.Models.ContestBatch", b =>
                {
                    b.Navigation("Candidates");
                });

            modelBuilder.Entity("Lorekeeper.Models.EditorConversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Lorekeeper.Models.EditorRevisionJob", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Lorekeeper.Models.EditorRevisionSession", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Lorekeeper.Models.GraphNode", b =>
                {
                    b.Navigation("IncomingEdges");

                    b.Navigation("OutgoingEdges");
                });

            modelBuilder.Entity("Lorekeeper.Models.IngestJob", b =>
                {
                    b.Navigation("Chunks");

                    b.Navigation("Events");

                    b.Navigation("ReportItems");
                });

            modelBuilder.Entity("Lorekeeper.Models.IngestSource", b =>
                {
                    b.Navigation("Jobs");

                    b.Navigation("SourceChunks");

                    b.Navigation("VectorFragments");
                });

            modelBuilder.Entity("Lorekeeper.Models.IngestSourceChunk", b =>
                {
                    b.Navigation("JobChunks");

                    b.Navigation("ReportItems");
                });

            modelBuilder.Entity("Lorekeeper.Models.LlmProvider", b =>
                {
                    b.Navigation("ChildModels");

                    b.Navigation("OAuthTokens");
                });

            modelBuilder.Entity("Lorekeeper.Models.OutlineConversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Lorekeeper.Models.Project", b =>
                {
                    b.Navigation("Acts");

                    b.Navigation("AiChangeBatches");

                    b.Navigation("Chapters");

                    b.Navigation("ContestBatches");

                    b.Navigation("EditorContextPreferences");

                    b.Navigation("EditorConversations");

                    b.Navigation("EditorRevisionJobs");

                    b.Navigation("EntityTypes");

                    b.Navigation("IngestJobs");

                    b.Navigation("IngestSources");

                    b.Navigation("Nodes");

                    b.Navigation("OutlineConversations");

                    b.Navigation("ProjectImportJobs");

                    b.Navigation("PublishAssets");

                    b.Navigation("PublishImagePlacements");

                    b.Navigation("PublishOutlineSelections");

                    b.Navigation("PublishProfiles");

                    b.Navigation("ResearchConversations");

                    b.Navigation("WebIngestCandidates");

                    b.Navigation("WritingCoachConversations");

                    b.Navigation("WritingSamples");
                });

            modelBuilder.Entity("Lorekeeper.Models.ProjectImportJob", b =>
                {
                    b.Navigation("ReportItems");
                });

            modelBuilder.Entity("Lorekeeper.Models.PublishAsset", b =>
                {
                    b.Navigation("CoverProfiles");

                    b.Navigation("ImagePlacements");
                });

            modelBuilder.Entity("Lorekeeper.Models.ResearchConversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Lorekeeper.Models.WritingCoachConversation", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
