// <auto-generated />
using System;
using Lorekeeper.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lorekeeper.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260429190928_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Lorekeeper.Models.GraphEdge", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EdgeType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FromNodeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Properties")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ToNodeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FromNodeId", "EdgeType");

                    b.HasIndex("ToNodeId", "EdgeType");

                    b.ToTable("GraphEdges");
                });

            modelBuilder.Entity("Lorekeeper.Models.GraphNode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT");

                    b.Property<string>("NodeType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Properties")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NodeType");

                    b.HasIndex("NodeType", "Key")
                        .IsUnique();

                    b.ToTable("GraphNodes");
                });

            modelBuilder.Entity("Lorekeeper.Models.LlmProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CredentialSourceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndpointUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CredentialSourceId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("LlmProviders");
                });

            modelBuilder.Entity("Lorekeeper.Models.OAuthToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProviderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("Scope")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId");

                    b.ToTable("OAuthTokens");
                });

            modelBuilder.Entity("Lorekeeper.Models.GraphEdge", b =>
                {
                    b.HasOne("Lorekeeper.Models.GraphNode", "FromNode")
                        .WithMany("OutgoingEdges")
                        .HasForeignKey("FromNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lorekeeper.Models.GraphNode", "ToNode")
                        .WithMany("IncomingEdges")
                        .HasForeignKey("ToNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromNode");

                    b.Navigation("ToNode");
                });

            modelBuilder.Entity("Lorekeeper.Models.LlmProvider", b =>
                {
                    b.HasOne("Lorekeeper.Models.LlmProvider", "CredentialSource")
                        .WithMany("ChildModels")
                        .HasForeignKey("CredentialSourceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CredentialSource");
                });

            modelBuilder.Entity("Lorekeeper.Models.OAuthToken", b =>
                {
                    b.HasOne("Lorekeeper.Models.LlmProvider", "Provider")
                        .WithMany("OAuthTokens")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Lorekeeper.Models.GraphNode", b =>
                {
                    b.Navigation("IncomingEdges");

                    b.Navigation("OutgoingEdges");
                });

            modelBuilder.Entity("Lorekeeper.Models.LlmProvider", b =>
                {
                    b.Navigation("ChildModels");

                    b.Navigation("OAuthTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
