// <auto-generated />
using Lorekeeper.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Lorekeeper.Persistence.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20260826200708_FinalizeReviewWorkflowTransition")]
partial class FinalizeReviewWorkflowTransition
{
    // The transition is intentionally SQL-only. Its target model is the
    // current AppDbContext snapshot; no generated model is needed to apply the
    // guarded cleanup operations.
}
